name: CI
on:
  pull_request:
  push:
jobs:
  test-f4pga:
    name: Test F4PGA
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: |
          nix build -L \
          ".#checks.$(nix eval --raw --impure --expr 'builtins.currentSystem').basys3-f4pga" \
          .#f4pga-arch-defs.ql-eos-s3
  build-pkgs:
    name: Build packages
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build -L .#python311.pkgs.litex-boards .#python3.pkgs.litex-boards
