name: CI
on:
  pull_request:
  push:
jobs:
  test-f4pga:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#checks.aarch64-darwin.basys3-f4pga .#f4pga-arch-defs.ql-eos-s3
  build-pkgs:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#python311.pkgs.litex-boards .#python3.pkgs.litex-boards
