name: CI
on: push
jobs:
  build-f4pga-arch-defs:
    name: Build f4pga-arch-defs
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build -L .#f4pga-arch-defs.{ql-eos-s3,xc7a50t}
  build-hol:
    name: Build HOL
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        kernel: [Stdknl, Expk]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build -L .#hol${{ matrix.kernel }}
  build-cakeml-asm:
    name: Build CakeML asm
    needs: build-hol
    runs-on: ubuntu-latest
    timeout-minutes: 900
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build -L .#cakeml.asm.{ag32,arm7,arm8,mips,riscv,x64}-{32,64}
  build-cakeml:
    name: Build CakeML
    needs: build-cakeml-asm
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build -L .#cakeml
  build-litex-boards:
    name: Build litex-boards
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-24.04-arm]
        interpreter: [python312, python313]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build -L .#${{ matrix.interpreter }}.pkgs.litex-boards
  test-f4pga:
    name: Test F4PGA
    needs: [build-f4pga-arch-defs, build-litex-boards]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build -L ".#checks.$(nix eval --raw --impure --expr 'builtins.currentSystem').basys3-f4pga"
  build-laptop-system:
    name: Build laptop system
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: CI_SAFE=1 nix build --impure -L .#darwinConfigurations.Liams-Laptop.system
  build-asahi-system:
    name: Build Asahi system
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: CI_SAFE=1 nix build --impure -L .#nixosConfigurations.liam-asahi.config.system.build.toplevel
  build-desktop-system:
    name: Build desktop system
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: CI_SAFE=1 nix build --impure -L .#nixosConfigurations.liam-desktop.config.system.build.toplevel
