name: CI
on:
  push:
    branches:
      - main
  pull_request:
env:
  CI_SAFE: 1
jobs:
  build-f4pga-arch-defs:
    name: Build f4pga-arch-defs
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build -L .#f4pga-arch-defs.{ql-eos-s3,xc7a50t}
  build-hol:
    name: Build HOL
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build -L .#hol --option cores 2
  build-litex-boards:
    name: Build litex-boards
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-24.04-arm]
        interpreter: [python312, python313]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build -L .#${{ matrix.interpreter }}.pkgs.litex-boards
  test-f4pga:
    name: Test F4PGA
    needs: [build-f4pga-arch-defs, build-litex-boards]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build -L ".#checks.$(nix eval --raw --impure --expr 'builtins.currentSystem').basys3-f4pga"
  test-openxc7:
    name: Test openXC7
    needs: [build-litex-boards]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build -L ".#checks.$(nix eval --raw --impure --expr 'builtins.currentSystem').basys3-openxc7" --option sandbox true
  build-laptop-system:
    name: Build laptop system
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --impure -L .#darwinConfigurations.Liams-Laptop.system
  build-asahi-kernel:
    name: Build Asahi kernel
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          swap-storage: false
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --impure -L .#nixosConfigurations.liam-asahi.config.boot.kernelPackages.kernel
  build-asahi-system:
    name: Build Asahi system
    needs: build-asahi-kernel
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          swap-storage: false
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --impure -L .#nixosConfigurations.liam-asahi.config.system.build.toplevel
  build-desktop-system:
    name: Build desktop system
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          swap-storage: false
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build --impure -L .#nixosConfigurations.liam-desktop.config.system.build.toplevel
  pin:
    name: Pin results
    needs:
      [
        build-f4pga-arch-defs,
        build-hol,
        build-litex-boards,
        test-openxc7,
        build-laptop-system,
        build-asahi-system,
        build-desktop-system,
      ]
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: liamolucko
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: |
          for branch in update main; do
            if [ ("$branch" = main -a \
              ('${{ needs.build.laptop-system.result }}' != success \
                -o '${{ needs.build.asahi-system.result }}' != success \
                -o '${{ needs.build.desktop-system.result }}' != success)) \
              -o ("$branch" = update -a "$GITHUB_HEAD_REF" != update_flake_lock_action) ]
            then continue
            fi

            for system in x86_64-linux aarch64-darwin aarch64-linux; do
              for chip in xc7a50t ql-eos-s3; do
                cachix pin liamolucko $branch-f4pga-arch-defs-$chip-$system $(nix eval --raw .#legacyPackages.$system.f4pga-arch-defs.$chip.outPath) || true
              done
              cachix pin liamolucko $branch-hol-$system $(nix eval --raw .#legacyPackages.$system.hol.outPath) || true
              for interp in python312 python313; do
                cachix pin liamolucko $branch-$interp-litex-boards-$system $(nix eval --raw .#legacyPackages.$system.$interp.pkgs.litex-boards.outPath) || true
              done
              cachix pin liamolucko $branch-nextpnr-xilinx-$system $(nix eval --raw .#legacyPackages.$system.nextpnr-xilinx.outPath) || true
            done

            cachix pin liamolucko $branch-laptop $(nix eval --impure --raw .#darwinConfigurations.Liams-Laptop.system.outPath) || true
            cachix pin liamolucko $branch-asahi $(nix eval --impure --raw .#nixosConfigurations.liam-asahi.config.system.build.toplevel.outPath) || true
            cachix pin liamolucko $branch-desktop $(nix eval --impure --raw .#nixosConfigurations.liam-desktop.config.system.build.toplevel.outPath) || true
          end
