name: Update dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - id: update
        uses: DeterminateSystems/update-flake-lock@v24
      - run: |
          gh pr close "${{ steps.update.outputs.pull-request-number }}"
          gh pr reopen "${{ steps.update.outputs.pull-request-number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
        if: ${{ steps.update.outputs.pull-request-number != '' }}
      - run: gh pr merge --auto "${{ steps.update.outputs.pull-request-number }}" --rebase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.update.outputs.pull-request-number != '' }}
